-- Minimal schema for Tests, Questions, Results
CREATE TABLE Tests (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Subject NVARCHAR(200) NOT NULL,
  ClassName NVARCHAR(50) NOT NULL,
  Date DATE NOT NULL,
  Time VARCHAR(10) NOT NULL,
  StartAt DATETIME NULL,
  EndAt DATETIME NULL,
  LinkExpiresAt DATETIME NULL,
  DurationMinutes INT NOT NULL DEFAULT 30,
  NumQuestions INT NULL,
  QuestionIdsJson NVARCHAR(MAX) NULL,
  ShuffleQuestions BIT NOT NULL DEFAULT 0,
  ShuffleOptions BIT NOT NULL DEFAULT 0,
  Type NVARCHAR(50) NOT NULL DEFAULT 'Objective',
  SubjectsJson NVARCHAR(MAX) NULL,
  Difficulty NVARCHAR(50) NOT NULL DEFAULT 'Easy',
  Status NVARCHAR(50) NOT NULL DEFAULT 'Scheduled'
);

CREATE TABLE Questions (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Subject NVARCHAR(200) NOT NULL,
  ClassName NVARCHAR(50) NOT NULL,
  QuestionText NVARCHAR(MAX) NOT NULL,
  Section NVARCHAR(200) NULL,
  ImageUrl NVARCHAR(MAX) NULL,
  Marks INT NOT NULL DEFAULT 1,
  OptionsJson NVARCHAR(MAX) NULL,
  CorrectIndex INT NULL,
  Difficulty NVARCHAR(50) NOT NULL DEFAULT 'Easy'
);

CREATE TABLE Results (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  TestId NVARCHAR(50) NULL,
  StudentName NVARCHAR(200) NOT NULL,
  ClassName NVARCHAR(50) NOT NULL,
  Subject NVARCHAR(200) NOT NULL,
  Score INT NOT NULL,
  OutOf INT NOT NULL,
  SubmittedAt DATETIME NOT NULL DEFAULT GETDATE(),
  AnswersJson NVARCHAR(MAX) NULL
);

CREATE TABLE StudyMaterials (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Title NVARCHAR(200) NOT NULL DEFAULT 'Study material',
  Subject NVARCHAR(200) NOT NULL,
  ClassName NVARCHAR(50) NOT NULL,
  WeekStart DATE NULL,
  FileUrl NVARCHAR(MAX) NOT NULL,
  FileName NVARCHAR(260) NULL,
  TeacherName NVARCHAR(200) NULL,
  UploadedAt DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Students (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  StudentName NVARCHAR(200) NOT NULL,
  ClassName NVARCHAR(50) NOT NULL,
  RollNumber NVARCHAR(50) NULL,
  MobileNumber NVARCHAR(20) NULL,
  CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);
